name: quotes_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  permission_handler: ^9.2.0
  firebase: ^9.0.2
  path: ^1.8.0
  firebase_database: any
  firebase_auth: ^3.3.11
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/favorite_management/
    - assets/images/quotes_management/
    - assets/images/user_management/

